services:
  testapp-django:
    platform: linux/amd64
    build:
      context: ../../src
      dockerfile: ../docker/pr/Dockerfile
    image: testapp-django
    environment:
      - ALLOWED_HOSTS="*"
    ports:
      - "8000:8000"